Repository fineanmol/hacktoberfest, pull requests merged in 2022-10, with the labels that each got.

#201 Added hello world in java and updated contributors list
  CONTRIBUTORS.md
  scripts/hello_world_prachipandeyy.java
Labels: hacktoberfest-accepted

#216 Contribution 8
  .DS_Store
  .idea/.gitignore
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  .vscode/settings.json
  CONTRIBUTORS.md
  Project 2.pdf
  Trees_Traversal.c
  check_cases.cpp
  game.c
  game.exe
  insertion sort.py
  qus.cpp
  readme.md
Labels: hacktoberfest-accepted

#360 Create word_ladder_2.cpp
  C++ Programs/word_ladder_2.cpp
Labels: duplicate

#349 BST in Java
  Bst(java).txt
Labels: Need Fix (Conflict Pull request), hacktoberfest-accepted

#384 ManusGupta.md
  profiles/ManusGupta.md
Labels: hacktoberfest-accepted

#393 Create sarthak_jain.md
  profiles/sarthak_jain.md
Labels: hacktoberfest-accepted

#394 Create hello_world_bobliuuu.rkt
  scripts/hello_world_bobliuuu.rkt
Labels: hacktoberfest-accepted

#396 hello page
  scripts/hello_page.php
Labels: hacktoberfest-accepted

#398 Create Linkedlist.cpp
  C++ Programs/Linkedlist.cpp
Labels: hacktoberfest-accepted

#400 Added First JS Game
  JS Games/Word Scramble/Output 1.png
  JS Games/Word Scramble/Output 2.png
  JS Games/Word Scramble/congrats.html
  JS Games/Word Scramble/index.html
  JS Games/Word Scramble/index.js
  JS Games/Word Scramble/stylesheet.css
Labels: hacktoberfest-accepted

#406 Create Palindrome Linked List
  C++ Programs/Palindrome Linked List
Labels: hacktoberfest-accepted

#413 Added Fibonacci Program
  Fibonacci.java
Labels: hacktoberfest-accepted

#418 Added set-matrix-zeros
  Set-matrix-zeros.cpp
Labels: hacktoberfest-accepted

#451 Create PDF Watermarker.py
  scripts/PDF Watermarker.py
Labels: hacktoberfest-accepted

#448 adding reverse k nodes of the linked list problem
  reverse_k_node_linked_list.cpp
Labels: hacktoberfest-accepted

#447 added Lowest Common ancestor of a BST Code
  Lowest_Common_Ancestor_BST.cpp
Labels: hacktoberfest-accepted

#446 Create Hello_Vedant.py
  scripts/Hello_Vedant.py
Labels: hacktoberfest-accepted

#442 Create snake-water-gun.py
  snake-water-gun.py
Labels: hacktoberfest-accepted

#440 added some concepts of programming
  C++ Programs/constructATree.cpp
  C++ Programs/heapImplementation.cpp
  C++ Programs/heightDiametreOfATree.cpp
  C++ Programs/kthMinElementInArray.cpp
  C++ Programs/morrisTraversal.cpp
Labels: hacktoberfest-accepted

#439 added minimum-time-to-make-rope-colorful.py
  minimum-time-to-make-rope-colorful.py
Labels: hacktoberfest-accepted

#437 Made changes to contributers.md
  CONTRIBUTORS.md
Labels: hacktoberfest-accepted

#432 Added kth Smallest Element in BST
  C++ Programs/KthSmallestElementInBST.cpp
Labels: hacktoberfest-accepted

#426 Added Calculator.py
  Calculator.py
Labels: hacktoberfest-accepted

#424 added 5 programs in C++ progrms folder
  C++ Programs/INFIXPOST.cpp
  C++ Programs/Insertion_sort_using_linked_list.cpp
  C++ Programs/Linear_Search.cpp
  C++ Programs/ParanthesisChecker.cpp
  C++ Programs/factorial.cpp
Labels: hacktoberfest-accepted

#419 Added Longest Substring Without Repeating Characters
  Longest-Substring-Without-Repeating-Characters.cpp
Labels: hacktoberfest-accepted

#412 WildCart Matching Problem
  C++ Programs/WildCard_Matching.c++
Labels: Need Fix (Conflict Pull request), hacktoberfest-accepted

#476 feat: add fleetimee
  profiles/Novian_Andika.md
Labels: hacktoberfest-accepted

#473 Created Rudreshwar.md
  profiles/Rudreshwar.md
Labels: hacktoberfest-accepted

#470 I added my profile
  profiles/Anish-Parkhi.md
Labels: hacktoberfest-accepted

#469 Update CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: hacktoberfest-accepted

#491 Add contribuitor Andre Almeida
  CONTRIBUTORS.md
  profiles/Andre_Almeida.md
  scripts/hello_world_aalmeida00.js
Labels: hacktoberfest-accepted

#490 adding my info to the contribution list
  CONTRIBUTORS.md
  profiles/Cesar_Infante.md
  scripts/Hello_World_Ceez.js
Labels: hacktoberfest-accepted

#489 contributed script
  scripts/hello-world_Jonathan-Meza.js
Labels: hacktoberfest-accepted

#486 Conditional Probability Example - Lorenzobattistela
  scripts/conditional_prob_Lorenzobattistela.py
Labels: hacktoberfest-accepted

#485 Hacktoberfest First commit
  CONTRIBUTORS.md
  profiles/RishiPratap.md
  scripts/hello.c
Labels: hacktoberfest-accepted

#484 Fix conflicts
  CONTRIBUTORS.md
  profiles/Randy_Asuncion.md
Labels: hacktoberfest-accepted

#481 Add Hello Word in TypeScript
  scripts/hellowWorld-WenDEUS.ts
Labels: hacktoberfest-accepted

#480 Hello world kotlin
  CONTRIBUTORS.md
  profiles/Caio_Icaro.md
  scripts/.idea/.gitignore
  scripts/.idea/kotlinc.xml
  scripts/.idea/libraries/KotlinJavaRuntime.xml
  scripts/.idea/misc.xml
  scripts/.idea/modules.xml
  scripts/.idea/vcs.xml
  scripts/hello_world_caioIcaro.kt
  scripts/scripts.iml
Labels: hacktoberfest-accepted

#522 Added my hello world
  scripts/hello_world_Shaheer.py
Labels: hacktoberfest-accepted

#518 ts greeting(Hello World meesage) added
  scripts/hello_world_thecoderishi.ts
Labels: hacktoberfest-accepted

#517 New Contribution commit
  CONTRIBUTORS.md
  profiles/Amith_Prasanth.md
  scripts/hello_world_amith.cpp
Labels: hacktoberfest-accepted

#516 Create HelloWorld in Java By Kevin
  scripts/HelloWorld in Java
Labels: hacktoberfest-accepted

#515 Add Abhishek Kevin Gomes
  profiles/Abhishek Kevin Gomes
Labels: hacktoberfest-accepted

#509 Hacktoberfest-2022
  profiles/Akshat_Agarwal.md
  scripts/hello_word_akshat_agarwal.js
Labels: hacktoberfest-accepted

#504 Hello world added in Scripts directory
  profiles/Piyush_Arora.md
  scripts/hello_world_piyush26arora.js
Labels: hacktoberfest-accepted

#503 Created Piyush_Arora.md profile in profiles directory
  profiles/Piyush_Arora.md
Labels: hacktoberfest-accepted

#502 Hello World Script
  scripts/helloworldscript.bye818.html
Labels: hacktoberfest-accepted

#499 added port-scanner.py
  profiles/rohan.md
  scripts/port-scanner.py
Labels: hacktoberfest-accepted

#495 Create HelloWorld.java
  scripts/HelloWorld.java
Labels: hacktoberfest-accepted

#493 Create ujjwalgupta.md
  profiles/ujjwalgupta.md
Labels: hacktoberfest-accepted

#514 Add Kevin in CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: hacktoberfest-accepted

#512 Added profile and hello world program (first-starter)
  CONTRIBUTORS.md
  profiles/Akshay_Kumar_Maurya.md
  scripts/hello_world_akshaykumarmaurya.kt
Labels: hacktoberfest-accepted

#500 Data script
  CONTRIBUTORS.md
  profiles/Victor_Pinheiro.md
  scripts/data-script.py
Labels: hacktoberfest-accepted

#498 Victorp
  CONTRIBUTORS.md
Labels: hacktoberfest-accepted

#496 Update CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: hacktoberfest-accepted

#494 Update CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: hacktoberfest-accepted

#521 Added Name to CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: hacktoberfest-accepted

#558 First commit
  CONTRIBUTORS.md
  profiles/osmnbtrclk.md
  scripts/Hello_osmnbtrclk.py
Labels: hacktoberfest-accepted

#555 Added my profile
  profiles/randyh0120.md
Labels: hacktoberfest-accepted

#548 Create Age Calculator
  scripts/Age Calculator
Labels: hacktoberfest-accepted

#546 Added the cpp code
  scripts/hello_world_Anurag-Nayak.cpp
Labels: hacktoberfest-accepted

#544 Create Prapul Muttineni
  profiles/Prapul Muttineni
Labels: hacktoberfest-accepted

#538 Ruby. First commit.
  scripts/hello_world_notafurryqwq.rb
Labels: hacktoberfest-accepted

#536 add mervyns
  CONTRIBUTORS.md
  profiles/Mervyns.md
  scripts/hello_world_mervyns.c
Labels: hacktoberfest-accepted

#535 add my name to contributors and create hello world
  CONTRIBUTORS.md
  scripts/simpleSlugGeneratorHelloWorld.php
Labels: hacktoberfest-accepted

#534 Search Insert Position
  Search Insert Position
Labels: hacktoberfest-accepted

#528 Change webp to png images.
  webp to png.py
Labels: hacktoberfest-accepted

#588 thanks for the hacktoberfest help!
  CONTRIBUTORS.md
Labels: hacktoberfest-accepted

#583 shivansh_javaCode
  scripts/buy_sell_stocks.java
Labels: hacktoberfest-accepted

#581 added Python programs asked in interviews
  profiles/Puneet_Awasthi.md
  python programs/check for a element in a linked list.py
  python programs/check for armstrong number.py
  python programs/deletion of a given element in a linked list.py
  python programs/frequency of elements in array.py
  python programs/middle element of linked list in single pass.py
  python programs/reverse a number.py
  python programs/reverse array in python.py
  python programs/single linked list.py
  python programs/sum of digits a number using recursion.py
  python programs/top two max elements.py
  scripts/Hello World_Puneet Awasthi.cpp
Labels: hacktoberfest-accepted

#580 added profile and cpp program
  profiles/Puneet_Awasthi.md
  scripts/Hello World_Puneet Awasthi.cpp
Labels: hacktoberfest-accepted

#578 hacktoberfest-2022
  scripts/sets.py
Labels: hacktoberfest-accepted

#575 added script and self introduction
  CONTRIBUTORS.md
  profiles/Smit_Vasoya.md
  scripts/hello_world_Smit-Vasoya-Tridhya.cpp
  scripts/hello_world_Smit-Vasoya-Tridhya.js
Labels: hacktoberfest-accepted

#573 Solution for diagonalDifference and my profile
  profiles/Leonan.md
  scripts/diagonalDifference.java
Labels: hacktoberfest-accepted

#565 Create Hello_world_Perfecto.py
  scripts/Hello_world_Perfecto.py
Labels: hacktoberfest-accepted

#614 HACKTOBERFEST
  CONTRIBUTORS.md
  scripts/hello_world.py
Labels: hacktoberfest-accepted

#610 Hello World by Arjav added
  scripts/hello_world_DeadliestDemon.cpp
Labels: hacktoberfest-accepted

#609 Added folder plans
  plans/.gitkeep
  plans/index.html
  plans/style.css
Labels: hacktoberfest-accepted

#597 Added Payal Jain in Contributors.md
  CONTRIBUTORS.md
Labels: hacktoberfest-accepted

#593 Added HelloWorld Script
  scripts/hello_world_VinayakSingoriya.py
Labels: hacktoberfest-accepted

#649 new push
  CONTRIBUTORS.md
  profiles/Piyush.md
Labels: hacktoberfest-accepted

#648 my hacktoberfest contribution
  profiles/Chiranjeev_Vishnoi.md
  scripts/hello_world_chiranjeevvishnoi.js
Labels: hacktoberfest-accepted

#647 Added C Code And Profile Details
  CONTRIBUTORS.md
  profiles/Tushar.md
  scripts/Mafia.c
Labels: hacktoberfest-accepted

#646 added a java code to find a perfect number
  scripts/PerfectNumber.java
Labels: hacktoberfest-accepted

#645 Added a Java Code to Reverse a linked list
  scripts/reverse_linkedlist.java
Labels: hacktoberfest-accepted

#644 hecktoberfest-2022
  1664996638953369138938319541360.jpg
Labels: hacktoberfest-accepted

#642 Create Nayan.md
  profiles/Nayan.md
Labels: hacktoberfest-accepted

#641 Create Glorious_Elijah.md
  profiles/Glorious_Elijah.md
Labels: hacktoberfest-accepted

#640 Create pratishshrivastava.md
  profiles/pratishshrivastava.md
Labels: hacktoberfest-accepted

#636 create hello_aditya.java
  scripts/hello_aditya.java
Labels: hacktoberfest-accepted

#635 Create Aayan.md
  profiles/Aayan.md
Labels: hacktoberfest-accepted

#632 Added name to contributors.md and added hello world program also added program to find missing number in ap sequence
  CONTRIBUTORS.md
  scripts/HelloWorld_DivyanshJha.cpp
  scripts/MissingNumberInSequence.cpp
Labels: hacktoberfest-accepted

#631 Create Rishav_Jaiswal.md
  profiles/Rishav_Jaiswal.md
Labels: hacktoberfest-accepted

#625 Added profile and script
  profiles/Prathmesh_Garule.md
  scripts/prathmesh_hello.cpp
  scripts/prathmesh_hello.exe
Labels: hacktoberfest-accepted

#689 Added Python Program
  scripts/plusminus.py
Labels: hacktoberfest-accepted

#770 Task 3
  scripts/hello_world_aratrik.js
Labels: hacktoberfest-accepted

#769 first contribution
  CONTRIBUTING.md
  profiles/AnkitKumar.md
Labels: hacktoberfest-accepted

#768 Added Vivek profile
  CONTRIBUTING.md
  profiles/vivek.md
Labels: hacktoberfest-accepted

#767 added profile and hello world program
  CONTRIBUTING.md
  profiles/Amogh_Patel.md
  scripts/hello_world_Amogh.c
Labels: hacktoberfest-accepted

#761 Create password_generator.js
  scripts/password_generator.js
Labels: hacktoberfest-accepted

#822 Added a hello world script
  profiles/Akarshit7.md
  scripts/hello_world_Akarshit7.cpp
Labels: hacktoberfest-accepted

#823 Contribution from Ashish for hacktoberfest2022
  CONTRIBUTING.md
  profiles/Ashish.md
  scripts/hello_world_ashish3121990.java
Labels: hacktoberfest-accepted

#821 contributed
  CONTRIBUTING.md
  profiles/Mansi_Yeole.md
  scripts/hello_world_mansi.cpp
Labels: hacktoberfest-accepted

#820 add name to contributers list and add profiles page
  CONTRIBUTING.md
  profiles/Pradhyum.md
Labels: hacktoberfest-accepted

#815 Added a hello world script
  scripts/hello_world_shemil076.js
Labels: hacktoberfest-accepted

#809 profile page changes and contributing markdown file changes
  CONTRIBUTING.md
  profiles/Guruvignesh.md
  scripts/hello_world_guruvignesh.js
Labels: hacktoberfest-accepted

#819 added a profile and modified contributors.md
  CONTRIBUTING.md
  profiles/ShrutiLicensed.md
Labels: hacktoberfest-accepted

#814 Added My Details In contributers.md
  CONTRIBUTING.md
Labels: hacktoberfest-accepted

#813 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: hacktoberfest-accepted

#805 added my hello world in JAVA
  CONTRIBUTING.md
  profiles/Prasad_Poojary.md
  scripts/hello_world_prasadpoojary.java
Labels: hacktoberfest-accepted

#812 Added snake game in python
  CONTRIBUTING.md
  scripts/Snakegame.py
Labels: hacktoberfest-accepted

#811 Create HelloWorldShivansh.py
  scripts/HelloWorldShivansh.py
Labels: hacktoberfest-accepted

#810 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: hacktoberfest-accepted

#806 Jha Raghav
  CONTRIBUTING.md
  profiles/Raghav.md
  scripts/hello_world_raghav_jha.js
Labels: hacktoberfest-accepted

#785 Hacktoberfest-2022
  CONTRIBUTING.md
  profiles/JanumalaAkhilendra
  scripts/Hello_World_Janumala_Akhilendra.cpp
Labels: hacktoberfest-accepted

#786 Added Hello World in JS by SomshuvraBasu
  scripts/hello_world_SomshuvraBasu.js
Labels: hacktoberfest-accepted

#787 Added Required Details
  CONTRIBUTING.md
  profiles/Priyanshu.md
  scripts/hello_world_priyanshu68.java
Labels: hacktoberfest-accepted

#788 Added hello_world_kbhavre.py to script folder
  scripts/hello_world_kbhavre.py
Labels: hacktoberfest-accepted

#789 PR for hacktoberfest
  CONTRIBUTING.md
  profiles/Nayaneeka.md
  scripts/hello_world_nexi9.java
Labels: hacktoberfest-accepted

#792 Create Calc.html
  Calculator-Site/Calc.html
Labels: hacktoberfest-accepted

#801 Added my version of Hello World
  scripts/hello_world_gamercreator1.js
Labels: hacktoberfest-accepted

#802 Hactoberfest2022 new branch
  CONTRIBUTING.md
  profiles/Kewpie134134.md
  scripts/hello_world_kewpie134134.js
Labels: hacktoberfest-accepted

#804 Windows in cpp
  profiles/divyanshu.md
  scripts/simplewindow_divyanshu.cpp
Labels: hacktoberfest-accepted

#756 Create hello_world_priyanka.cpp
  scripts/hello_world_priyanka.cpp
Labels: hacktoberfest-accepted

#755 add hello_world_chi.sh in a fun way
  scripts/hello_world_chi.sh
Labels: hacktoberfest-accepted

#754 Add a more creative Python hello world
  scripts/hello_world_unixfy.py
Labels: hacktoberfest-accepted

#753 Add files via upload
  scripts/Hello_world_Dhara.cpp
Labels: hacktoberfest-accepted

#784 Nitin added his bio
  CONTRIBUTING.md
Labels: hacktoberfest-accepted

#750 Commited Profile, Script and Updated CONTRIBUTING.md
  CONTRIBUTING.md
  profiles/Amit-Das.md
  scripts/Hello_World_das-amit.bhai
Labels: hacktoberfest-accepted

#751 Hafeez profile add
  CONTRIBUTING.md
  profiles/Hafizur_Rahman.md
  scripts/script_hafeez.js
Labels: hacktoberfest-accepted

#752 Modified CONTRIBUTING.md and added script file
  CONTRIBUTING.md
  scripts/hello_world_vanam30.py
Labels: hacktoberfest-accepted

#749 Hacktoberfest 2022
  binarysearch09876544567.py
Labels: hacktoberfest-accepted

#748 Added Name, profile page and script
  profiles/Tanuj_Kalonia.md
  scripts/hello_world_Tanuj_Kalonia.cpp
Labels: hacktoberfest-accepted

#718 Create Hello_world_Rohan-Somadder.py
  scripts/Hello_world_Rohan-Somadder.py
Labels: Star ⭐️ repo to earn hacktoberfest label

#717 sayHello()
  scripts/Hello_World_Music.java
Labels: Star ⭐️ repo to earn hacktoberfest label

#716 Added My Bio
  CONTRIBUTING.md
Labels: Star ⭐️ repo to earn hacktoberfest label

#724 Updated CONTRIBUTING.md file
  CONTRIBUTING.md
  scripts/hello_world_mayank_thakur.py
Labels: Star ⭐️ repo to earn hacktoberfest label

#727 Updated CONTRIBUTING.md
  CONTRIBUTING.md
Labels: Star ⭐️ repo to earn hacktoberfest label

#734 Script and Name added
  CONTRIBUTING.md
  scripts/hello_world_Soham.cpp
Labels: Star ⭐️ repo to earn hacktoberfest label

#735 -task 1 : Contributing.md
  CONTRIBUTING.md
Labels: Star ⭐️ repo to earn hacktoberfest label

#736 My_Contributions
  .DS_Store
  CONTRIBUTING.md
  profiles/Gem.md
  scripts/Hello_World_GS.js
Labels: Star ⭐️ repo to earn hacktoberfest label

#740 update CONTRIBUTING.md
  CONTRIBUTING.md
  scripts/hello_world_goswamiprad.py
Labels: Star ⭐️ repo to earn hacktoberfest label

#742 Hacktoberfest 2022
  CONTRIBUTING.md
  profiles/Lakshya.md
  scripts/hello_world_yolakshya19.cpp
Labels: Star ⭐️ repo to earn hacktoberfest label

#743 HACKTOBERFEST_2022
  CONTRIBUTING.md
  profiles/SURAJ_KESHARI.md
  scripts/Bubble Sort in Go Lang
  scripts/Golang Merge Sort Algorithm.go
  scripts/HELLO_WORLD_SURAJ.cpp
  scripts/Python Program for Bubble Sort.py
  scripts/Python Program for Merge Sort.py
Labels: Star ⭐️ repo to earn hacktoberfest label

#744 Commits to participate in hacktoberfest
  CONTRIBUTING.md
  profiles/FabianCristancho.md
  scripts/hello_world_fabiancristancho.js
Labels: hacktoberfest-accepted, Star ⭐️ repo to earn hacktoberfest label

#831 Created Calculator.c
  .vscode/tasks.json
  Calculator-Site/Calculator
  Calculator-Site/Calculator.c
  Calculator-Site/Calculator.dSYM/Contents/Info.plist
  Calculator-Site/Calculator.dSYM/Contents/Resources/DWARF/Calculator
Labels: Star ⭐️ repo to earn hacktoberfest label

#830 Name added
  CONTRIBUTING.md
Labels: Star ⭐️ repo to earn hacktoberfest label

#829 first open source contribution
  CONTRIBUTING.md
  profiles/KiranRai.md
  scripts/hello_world_kiran.java
Labels: Star ⭐️ repo to earn hacktoberfest label

#715 created_program_file
  profiles/Prabhu.md
  scripts/hello_world_prabhu.py
Labels: Star ⭐️ repo to earn hacktoberfest label

#713 Added megan-taylor to Contributors list
  CONTRIBUTING.md
  scripts/hello_world_taylor-g592.kt
Labels: Star ⭐️ repo to earn hacktoberfest label
